eureka:
  client:
    serviceUrl:
      defaultZone: ${eurekahost}
  instance:
    hostname: ${HOST_NAME}
    nonSecurePort: 80
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'